new compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,52 +1,152 @@
-#!/bin/sh
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
+# fail fast
+set -e
+
+# debug
+# set -x
+
+# clean up leaking environment
+unset GIT_DIR
+
+# parse and derive params
 BUILD_DIR=$1
 CACHE_DIR=$2
-METEOR_HOME=$BUILD_DIR/.meteor/local
-PATH=$METEOR_HOME/usr/bin:$METEOR_HOME/usr/lib/meteor/bin:$PATH
-
-# Unfortunately heroku buildpacks don't let you pass parameters
-# to this script, so if you want to change the version of meteor,
-# you'll have to fork and hard-code this.
-METEOR_VERSION=0.9.4
-
-fetch_meteor() {
-  if [ -f "$METEOR_HOME/usr/bin/meteor" ] ; then
-    # Skip if meteor is already fetched
-    return
-  fi
-
-
-  PACKAGE=meteor_${METEOR_VERSION}-1_amd64.deb
-
-  echo "Fetching meteor deb package"
-  curl -o "$CACHE_DIR/$PACKAGE" "http://d3sqy0vbqsdhku.cloudfront.net/${PACKAGE}"
-
-  echo "Unpacking meteor"
-  [ ! -d "$METEOR_HOME" ] && mkdir -p "$METEOR_HOME"
-  ar p "$CACHE_DIR/$PACKAGE" data.tar.gz | tar -C "$METEOR_HOME" -zxf -
-}
-
-build() {
-  ( 
-    cd $BUILD_DIR
-    echo "Building meteor bundle"
-    meteor bundle $CACHE_DIR/bundle.tar.gz 
-    mkdir -p $BUILD_DIR/.meteor/local/build
-    tar -zxf $CACHE_DIR/bundle.tar.gz --strip-components 1 -C $BUILD_DIR/.meteor/local/build
-    rm $CACHE_DIR/bundle.tar.gz
-  )
-}
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+BUILDPACK_DIR="$(dirname $(dirname $0))"
 
 [ ! -d $BUILD_DIR ] && mkdir $BUILD_DIR
 [ ! -d $CACHE_DIR ] && mkdir $CACHE_DIR
 
-fetch_meteor
-build
+function error() {
+  echo " !     $*"
+  exit 1
+}
 
-echo "Checking for post_compile script"
-if [ -f $BUILD_DIR/bin/post_compile ] ; then
-    echo "-----> Running post_compile hook"
-    chmod +x $BUILD_DIR/bin/post_compile
-    $BUILD_DIR/bin/post_compile
+function mktmpdir() {
+  dir=$(mktemp -t node-$1-XXXX)
+  rm -rf $dir
+  mkdir -p $dir
+  echo $dir
+}
+
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
+
+function run_npm() {
+  command="$1"
+
+  cd "$BUILD_DIR"
+  HOME="$BUILD_DIR" $VENDORED_NODE/bin/node $VENDORED_NODE/bin/npm $command 2>&1 | indent
+
+  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+    echo " !     Failed to $command dependencies with npm"
+    exit 1
+  fi
+}
+
+function package_download() {
+  engine="$1"
+  version="$2"
+  location="$3"
+
+  mkdir -p $location
+  package="http://s3pository.heroku.com/$engine/v$version/$engine-v$version-linux-x64.tar.gz"
+  echo " - downloading and extracting $engine from $package" | indent
+  curl $package -s -o - | tar -zxf  - -C $location --strip 1
+}
+
+echo "-----> Resolving engine versions"
+
+#TODO: Fix package.json loading
+#if [ -f "${BUILD_DIR}/package.json" ]; then
+#  requested_node_ver=$(cat $BUILD_DIR/package.json | $LP_DIR/vendor/jq -r .engines.node)
+#fi
+#temporary - load from nodeversion
+requested_node_ver=""
+if [ -f "${BUILD_DIR}/nodeversion" ]; then
+  echo " - nodeversion file detected, using for semvar" | indent
+  requested_node_ver=$(cat $BUILD_DIR/nodeversion)
+  echo " - requested version: $requested_node_ver" | indent
 fi
+# add a warning if no version of node specified
+if [ "$requested_node_ver" == "" ]; then
+  requested_node_ver="0.10.29"
+  echo
+  echo "No version of Node.js specified in nodeversion, using '${requested_node_ver}'" | indent
+  echo
+fi
+
+NODE_VERSION=$(curl --silent --get --data-urlencode "range=${requested_node_ver}" https://semver.io/node/resolve)
+echo "Using Node.js version: ${NODE_VERSION}" | indent
+
+# vendor directories
+VENDORED_NODE="$(mktmpdir node)"
+VENDORED_MODULES="$(mktmpdir modules)"
+
+# download and unpack packages
+echo "-----> Fetching Node.js binaries"
+package_download "node" "${NODE_VERSION}" "${VENDORED_NODE}"
+
+# setting up paths for building
+PATH="$VENDORED_NODE/bin:$VENDORED_MODULES/bin:$PATH"
+INCLUDE_PATH="$VENDORED_NODE/include"
+export npm_config_prefix="$VENDORED_MODULES"
+export CPATH="$INCLUDE_PATH"
+export CPPPATH="$INCLUDE_PATH"
+
+############################################
+# install meteorite
+############################################
+echo "-----> Installing meteorite with npm"
+
+run_npm "install meteorite fibers -g"
+echo "Meteorite installed" | indent
+
+METEOR_BUILD_DIR="$BUILD_DIR/.meteor/heroku_build"
+mkdir -p "$HOME"
+############################################
+# install meteor + packages through mrt
+# bundle, and install into app/
+############################################
+cd $BUILD_DIR
+echo "Installing meteor" | indent
+
+# Using different folder to prevent install script form deleting packages file
+VENDORED_METEOR="$(mktmpdir meteor)"
+curl https://install.meteor.com | HOME="$VENDORED_METEOR" /bin/sh | indent
+echo "Meteor installed" | indent
+
+echo "Installing packages" | indent
+HOME="$BUILD_DIR" mrt install --force | indent
+echo "Building meteor bundle" | indent
+HOME="$VENDORED_METEOR" "$VENDORED_METEOR"/.meteor/meteor bundle "$CACHE_DIR"/bundle.tar.gz 2>&1 | indent
+
+mkdir -p "$METEOR_BUILD_DIR"/app
+tar -zxf "$CACHE_DIR"/bundle.tar.gz --strip-components 1 -C "$METEOR_BUILD_DIR"/app
+rm "$CACHE_DIR"/bundle.tar.gz
+############################################
+
+# vendor node into the slug
+PATH="$METEOR_BUILD_DIR/bin:$PATH"
+echo "-----> Vendoring node into slug"
+mkdir -p "$METEOR_BUILD_DIR/bin"
+cp "$VENDORED_NODE/bin/node" "$METEOR_BUILD_DIR/bin/node"
+
+echo "-----> Move to app directory: /programs/server"
+cd "$METEOR_BUILD_DIR"/app/programs/server
+
+echo "-----> Run npm install"
+npm install
+
+# copy over environment
+echo "-----> Copy over environment profile.d scripts"
+mkdir -p $BUILD_DIR/.profile.d
+cp "$BUILDPACK_DIR/mongo.sh" $BUILD_DIR/.profile.d/mongo.sh
+cp "$BUILDPACK_DIR/mailgun.sh" $BUILD_DIR/.profile.d/mailgun.sh
